### ISSUE TITLE
Ball positions incorrectly

### ISSUE THREAD

**Issue by d0n3val** [Paui8/EgypciansProject1#17]
Prio C
Repro shoot balls with odd angles
Behaviour: ball "teleports" to an impossible position  (the yellow one on the leftmost part of the screen, second row starting from below)

![image](https://cloud.githubusercontent.com/assets/627698/15388353/dd845802-1db1-11e6-83e1-a9bf68fd3c27.png)

**Comment by cireks** [comment]
board already giving spaces for the balls to be placed bellow line 5
